name: timecode_tod_viewer
description: Camera sync timecode display — HH:MM:SS:FF

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#111111"

flutter:
  uses-material-design: true
